# Run with MySQL:
# mvn spring-boot:run "-Dspring-boot.run.profiles=mysql"

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/leavedb}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD}

spring.flyway.enabled=true

spring.jpa.hibernate.ddl-auto=validate

spring.h2.console.enabled=false
